# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Deploy basket-api

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - deploy
  workflow_run:
    workflows: ["basket-api"]
    branches: [dev]
    types: [completed]

env:
  CHART: basket-api
  NAMESPACE: eshop
  CHART_ROOT: deploy/k8s/helm

jobs:
  deploy-to-k8s:
    #if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    if: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: ./.github/workflows/composite/deploy-helm
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          resource_group: ${{ secrets.RESOURCE_GROUP }}
          registry_host: ${{ secrets.REGISTRY_HOST }}
          chart: ${{ env.CHART }}
          chart_root: ${{ env.CHART_ROOT }}
          namespace: ${{ env.NAMESPACE }}
