# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: identity-api

on:
  workflow_dispatch:
  push:
    branches:
      - dev

    paths:
      - src/BuildingBlocks/**
      - src/Services/Identity/**
      - .github/workflows/identity-api.yml

  pull_request:
    branches:
      - dev

    paths:
      - src/BuildingBlocks/**
      - src/Services/Identity/**
      - .github/workflows/identity-api.yml
env:
  SERVICE: identity-api
  IMAGE: identity.api

jobs:
  BuildContainersForPR_Linux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: ./.github/workflows/composite/build
        with:
          service: ${{ env.SERVICE }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}

  BuildLinux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: ./.github/workflows/composite/build-push
        with:
          service: ${{ env.SERVICE }}
          registry_host: ${{ secrets.REGISTRY_HOST }}
          registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
          image_name: ${{ env.IMAGE }}
          registry_username: ${{ secrets.USERNAME }}
          registry_password: ${{ secrets.PASSWORD }}
