# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Deploy webmvc

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - deploy
  workflow_run:
    workflows: ["webmvc"]
    branches: [dev]
    types: [completed]

env:
  CHART: webmvc
  NAMESPACE: eshop
  CHART_ROOT: deploy/k8s/helm

jobs:
  deploy-to-k8s:
    #if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    if: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: ./.github/workflows/composite/deploy-helm
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          resource_group: ${{ secrets.RESOURCE_GROUP }}
          registry_host: ${{ secrets.REGISTRY_HOST }}
          chart: ${{ env.CHART }}
          chart_root: ${{ env.CHART_ROOT }}
          namespace: ${{ env.NAMESPACE }}
